### PR TITLE
New functionality, second pass

### PR DESCRIPTION
**Pull request by Horsey-**
Hi Dan, I saw you were releasing new versions of the theme. I wanted to try again submitting a pull request for Stepartist metadata and Group/Folder display on ScreenSelectMusic and ScreenEvaluation common. 

- resized the Songdescription to fit group/folder name (slightly resized other elements to accommodate, and using conditionals so that the look and feel are unchanged in Course Mode, see below)
- adds a new Quad to Eval for group/folder name, using a lighter colour to visually be distinct from the name of the song, as well as being slightly smaller in size
- adds and uses a new png asset, stepartistbubble.png that mimics the stepartist bubble from 3.95
- adds a new ThemePref for displaying the group or filesystem folder name in Simply Love Options
- marquees through chart Credit, Description, ChartName for .ssc files (displays only Credit for .sm files)
_-The marquee works such that if no Description or ChartName tag is found, the Credit tag is shown instead. If there is no Credit tag, the current behaviour is unchanged
-The Credit/Description/ChartName texts preserve the most recent update to the theme whereby emojis are not diffused black (not shown below)._

This file is live -like many others- on the r21 Dropbox. I have been fixing Credit metadata in all released r21/SM5 content since roughly 2016, and have gone back in time somewhat for files released before then.
proofofconcept

This is just showing the three different possibilities for what can be displayed. 
proofofconcept2

This is the Evaluation screen.
proofofconcept3

Another view of the evaluation Screen. (yo dude, what pack is that from? oh sick I'll go download it!)
2018-10-01 02_06_32-simply love

This is an example of "Group" being shown in the SongDescription, configurable in Simply Love Options
2018-10-01 01_55_56-simply love

The quad for SongDescription resizes in Course Mode to retain the current look. The folder/group text is blank on this screen.
2018-10-01 02_14_29-simply love

Course Mode's Evaluation screen is also similarly unchanged.
2018-10-01 02_19_00-simply love

### CODE REVIEW

**Comment by Horsey-** [comment]
I just realized that I forgot to adjust the y position of the song rate overlay. I'll get that integer tomorrow, I need sleep lol.

**Comment by RodentVienna** [comment]
hi, while at it, can we have BPM and Song Length displayed in results screen? :) I would be cool enough with emoticonized variants of those ;P

**Comment by dguzek** [comment]
I appreciate that you took the time to clean this up and resubmit it.  I especially appreciate how helpful and fleshed out your pull request description is.  The gifs go a long way in quickly and effectively illustrating what changes you've made.

I am okay with the idea of marquee-ing through chart Credit, Description, and Chartname.  I'd want to spend a little time thinking how I'd want to handle the code for it, and will probably end up not using the code in this pull request. (A new theme should really be designed and implemented.)

I don't understand how displaying the filesystem folder of the current song in ScreenSelectMusic is helpful to anyone, but it clearly must be helpful to you or else you wouldn't have bothered to implement it.  How does it help you?  (A new theme should be designed and implemented.)

I like the intent of stepartistbubble.png but not its aesthetic.  The triangle being pushed to the edge looks strange to my eye given what I expect of SL's existing aesthetic.  (A new theme should be designed and implemented.)

Displaying group name in ScreenEvaluation is helpful, but I *really* don't like the cramped aesthetic.  I'm torn.  (A new theme should be designed and implemented.)

*Simply Love Options* is way too crowded already (similar to *ScreenPlayerOptions2*).  I like having all these options, but I don't like the UI clutter, and I don't like how confusing it is for novice players.  Novice players (and novice machine operators) should always, *always* be considered when adding new features.  (A new theme should be designed and implemented.)

---

> I saw you were releasing new versions of the theme.

I wasn't supposed to, but life had other plans for me.

**Comment by Horsey-** [comment]
the Song folder concept is helpful to see what pack a song is from, -especially- when you sort by anything other than group, especially in Evaluation screenshots.

I'm glad you're down with the Marquee idea at the very least; can I edit the commit to shorten the triangle? The aesthetic of boxes really irked me because the triangle in the original gave the eye a way to see where the information was coming from, much like the "counts as two rounds"

**Comment by RodentVienna** [comment]
about the group folder name: if you have 5000 songs on the machine, and use sort a lot, then  many identically looking simfiles are there next to each other, which make it impossible to identify the pack they belong to at first sight. the current workflow to recognize the pack would be to identify the song in the sort mode, then exit sort mode to Group Sort, then browse up to the folder name. i use this a lot to identify favorable songs. like, to match the 100 versions of Bloody Tears... not everything is about creating a new theme, although i understand you want to quit and say that in favor of you doing again more work. i just tried to explain the usefulness :)

**Comment by dguzek** [comment]
Does the *Marquee* effect take place anywhere other than ScreenSelectMusic and ScreenEvaluation?

I've reimplemented the functionality and want to ensure I'm covering all the bases.

**Comment by Horsey-** [comment]
this only implemented the marquee on ScreenSelectMusic and Evaluation common

**Comment by dguzek** [comment]
Thank you for your effort with this pull request, your diligence in cleaning it up and resubmitting it, your dedication to the community, and your overall enthusiasm for dance games.  I am going to close it at this time as I believe it has been effectively supplanted by bbf6e6cb840e261d71c8c659fbaa1e108abd6c8c.

**Pull request closed without merging**
