### PR TITLE
Minor font tweaks

### PR DESCRIPTION
**Pull request by sangyeolbaek**
These adjustments seem trivial and driven by OCD, but some explanations:

- **jfonts**: the "5" and "9" seemed to have a bit less spacing than any other digit
- **miso**: the "3" seemed to have a bit more spacing than all other digits
- **wendy small**: the "7" seemed to have a bit less spacing than all other digits

### CODE REVIEW

**Comment by dguzek** [comment]
Thanks for this pull request.

I think these changes are good and sensible, but I'm concerned about complaints arising out of changes made to the Love judgment font, because it appears prominently in gameplay.  See #112 for similar complaints.

I will merge this if you can redo the pull request only include BitmapText font changes.  I also encourage you to learn about the `git branch` command and not do your work on your *master* branch to prevent yourself future headaches. 🙂

**Comment by ianklatzco** [comment]
@sangyeolbaek you can try using `git rebase -i HEAD^` if you want to try editing your commit.

@dguzek what's the reasoning for branching? (ie, what are the headaches we're trying to avoid?)

So far I've gathered (given an open PR from fork/master to upstream/master):
* If commits are added to fork/master, they are added to the PR.
* If master receives changes from elsewhere while this PR is still open, does that require rebasing this PR on top of those changes? No, it's standard merge process for any two different branches.

So, is the reason to recommend it more of a "we should encourage new devs to use branch-based dev", or are there other issues that arise out of using master that we should be aware of?

**Comment by sangyeolbaek** [comment]
I just reverted the graphics to their original states (in other words, I committed the original files of the judgments)

I'm pretty new to GitHub btw, so I'm open to any tips

**Comment by ianklatzco** [comment]
@dguzek no worries - you didn't cause me any confusion! This is a point of git I've been curious about for a while (Sangyeol was making changes on ddrillini repos yesterday that raised the same question) and I wanted to know what you thought about the matter c:

@sangyeolbaek That looks good to me! If you want to learn a \~new thing\~, you can try closing this pull request, making the same changes on a separate branch, and opening a new pull request with those changes. That way, you'll make the PR with a new branch instead.

**Comment by dguzek** [comment]
Thanks, @sangyeolbaek !

**Comment by ianklatzco** [comment]
👏👏👏👏👏👏👏 go sangyeol!!!!

**Pull request merged**
