### PR TITLE
Handle negative measure count at the start of a song

### PR DESCRIPTION
**Pull request by teejusb**
- Sometimes currMeasure might be negative. If we have a stream at the start, denote that extra space as a break.

### CODE REVIEW

**Comment by quietly-turning** [comment]
Thanks for this PR!

In the interest of time and not having you resubmit, I cherry-picked your commit to sidestep the two merge commits here.

**Comment by teejusb** [comment]
Do the merge commits affect anything? They "Files changed" tab shows no other files changed besides the main commit.

**Comment by quietly-turning** [comment]
> Do the merge commits affect anything?

Not really.  It's more history to scroll through when I'm looking for some specific commit/historical line of code/etc. to link to, but I don't believe there's more to it than that.

**Comment by teejusb** [comment]
Is there a way to make those merges not show up? I do them to fetch upstream changes to make sure there aren't any merge conflicts when pushing to my branch. Is the actual methodology to make to the PR first before fetching upstream changes? That seeeeeeeems like it's incorrect but I'm not well versed enough in git-fu.

**Comment by fent** [comment]
> Is there a way to make those merges not show up?

you can try rebasing instead of merging. rebasing will put your commits on top of any upstream commits

> In the interest of time and not having you resubmit, I cherry-picked your commit to sidestep the two merge commits here.

doesn't github have the "squash and merge" option that squashes everything into one commit, even merges?

**Comment by teejusb** [comment]
> > Is there a way to make those merges not show up?
> 
> you can try rebasing instead of merging. rebasing will put your commits on top of any upstream commits
> 
Thanks! I'll take a look into it. On Windows, I just use the GitHub GUI since it's usually sufficient but yeah I can definitely do that as well.

> > In the interest of time and not having you resubmit, I cherry-picked your commit to sidestep the two merge commits here.
> 
> doesn't github have the "squash and merge" option that squashes everything into one commit, even merges?
/shrug! But that sounds like what I want. Will take a look. Thanks!

**Comment by quietly-turning** [comment]
> doesn't github have the "squash and merge" option that squashes everything into one commit, even merges?

I'll look for that next time this comes up.  Thanks for the suggestion!

**Pull request closed without merging**
