### PR TITLE
Add support for favoriting songs

### PR DESCRIPTION
**Pull request by CrashCringle12**
There are two ways to favorite a song:
1) Inputting the specified code on ScreenSelectMusic
2) Inputting the specified code on ScreenEvaluation

The pad codes are defined in metrics.ini as CodeMessages; I currently have this CodeMessage set to the spin pattern since that's what we've been using for the past couple years at our cab, but I'm open to changing it if that's not suitable for the broader community. Presently if you do RDLUR it will favorite/unfavorite the song you are currently hovered over (or the last played song if in ScreenEvaluation).

The bulk of the code for favorites is in the FavoritesHandler.lua. The sound that's made when you add a favorite is the _unlock sound that was in SL at a point, but was since removed from upstream. 

There is a check for whether or not the user is using itgmania, if they're not using itgmania it will use *legacy* behavior and read files from the ``Other`` directory. 

Each player's favorites can be accessed via SL[pn].Favorites

Favorites are shown in the music wheel in 2 ways. The most notable is the SL-heart that appears next to the song. Blue for P1 and Red for P2.  

Favorites are stored in a file called FavoriteSongs.txt located in their profile directory. Here is an example of such a file:
```
---Lamar's Favorites
UPS 3/Mouse Dance
UPS 4/Gee
Easy As Pie 6/NoNoNo
FA and Chill 2/BIPP
Cringle Conservation/call me maybe
Unsorted/My Shiny Teeth and Me
Cringle Asylum/Say So
Cringle Asylum/Dynamite
UPS 4/Daddy
Stupid Doubles Charts/Eskimo
Sharpnelshortz/Bluesky
UPS 5/Crazy
SPEEEDCOOOORE 4/Yura-Yura Sweet Genocide - [Rynker]
SV3/Summertime Sadness - [teejusb]

```

When the player goes into the Favorite's sort they will see all of these songs under a folder called "Lamar's Favorites"

Lines that begin with --- mark the beginning of a folder. So one could use this to create "custom folders" as shown below:

```
---Lamar's Favorites
UPS 3/Mouse Dance
UPS 4/Gee
Easy As Pie 6/NoNoNo
FA and Chill 2/BIPP
Cringle Conservation/call me maybe
Unsorted/My Shiny Teeth and Me
J.U.M.P.S./Lips Are Movin
AJAX's Small Assortments/[AJAX] Better Off Alone
Cringle Conservation/Break It
Cringle Conservation/Addicted To A Memory v3
Ben Speirs' SPEIRMIX Galaxy/Thinking Out Loud
chewi pack 2017/My Neck, My Back (Lick It)
Valex's Magical 4-Arrow Adventure 10/Fake!Fake!Fake!
Cringle Asylum/Say So
Cringle Asylum/Dynamite
UPS 4/Daddy
Stupid Doubles Charts/Eskimo
Sharpnelshortz/Bluesky
---Lamar's New Picks
Cringle Asylum/Dynamite
UPS 4/wah-propaganwah (habstrakt remix) (ddrillini remix)
Zyroplex 2nd Edition/Twerkout Revolution (Zyroplex)
Jimbo and MWOK Tourney 2010/Licky (Work It Out)
S.M.H. 4/Brain Power - [Cardboard Box]
Cringle Conservation/Gee
dbk6/Boys
Easy As Pie/Kung Fu Beat
PROJECT OBSIDIAN/Flip Flap
DDR A20/Alone
Italian Zarranza/Luna Park [O]
Ben Speirs' SPEIRMIX Galaxy/Sweet Lovin'
Unsorted/Bla Bla Bla (WhiteDR Mario)
dbk3/Oh v2
UPS 5/Wake Up
Crapyard Scent/Tunak Tunak Tun
Mungyodance 3/Destination Unknown
UPS 5/Crazy
---Lamar's Super Fun Awesome charts
SPEEEDCOOOORE 4/Yura-Yura Sweet Genocide - [Rynker]
SV3/Summertime Sadness - [teejusb]
5guys1pack (Null Offset)/I Love You
Mute Sims 7/Tricky Disco (DJs From Mars Remix)
UPS 4/B12
D.O.W.N.S. 4/Time to Body Wash
Stupid Doubles Charts/My First Kiss
Easy As Pie 6/Bad Guy
Valex's Magical 4-Arrow Adventure 10/Barracuda
SV3/Drop Girl - [Horsey]
D.O.W.N.S. 4/Right Round
Zyroplex 2nd Edition/Bumble Bee
Mudkyp 7th Gen/Peanut Butter
Italian Zarranza/Soldi [O]
Cedar Style/Live Forever (Ceder Style)
SPEEEDCOOOORE 4/Miracle 5ympho X - [Aoreo]
PSU Speed Charting Pack/Bacon Pancakes New York
FA and Chill 2/Hello
UPS 3/Bustin
Koreyja 2/What is Love
Shpadoinkle #9/Who's Laughing Now
Squeaky Beds and Leaky Faucets DX/Omae Wa Mou
Best of Gazebo/Fancy Footwork (Crookers Remix)
Piece of Cake/(-[Jayce]-) - Push Up - [09]
Shpadoinkle #6/Five More Hours
---Songs to beat
Squeaky Beds and Leaky Faucets DX/Melon Soda
MrThatKid SM5 Conversions/Echo
Shpadoinkle #6/With You
UPS 3/Backwards
U.P.S. 2/Trancing Pulse (Random)
Xynn's LVTS STREAM Pack/Eskimo
D.O.W.N.S. 4/Down
RIME's Collection/Radio Song
Whack-a-pack/Daddy (Retro)
Squeaky Beds and Leaky Faucets DX/Too True
Zetorux/Round and Round
Gay4Gimmix 3/(-[Jayce]-) - Technyancolor - [11]
Cringle Construction/My Sidepiece
Cringle Asylum/Best Friend
UPS 4/Sunny After Rain [Telperion]
Cringle Isle/Delightful Day
```
image

You might notice that the numbers in the screenshot don't align with the amount of songs shared above. If a favorite song is not found, it will just be ignored. It will include all the songs that it was able to find. In this case, my laptop has significantly less songs so only a few of my favorites appear.

-----------------------------------------------------

### CODE REVIEW

**Comment by teejusb** [comment]
I have a working implementation for favorites as well. I'll keep this PR up to compare/contrast implementations and likely get the feature in for next release.

**Comment by Horsey-** [comment]
The favorites icon doesn't update when you remove a favorite. You have to essentially finish your set and start a new set to see a favorite removed from a favorites list.

**Comment by CrashCringle12** [comment]
> The favorites icon doesn't update when you remove a favorite. You have to essentially finish your set and start a new set to see a favorite removed from a favorites list.

Thanks for pointing that out. Should be fixed now. Should also be properly sorted alphabetically now as well.

**Comment by teejusb** [comment]
I added support for favorites here in this commit (as mentioned in my first comment).

https://github.com/Simply-Love/Simply-Love-SM5/commit/1ad68abaf555a1a66cfda917fb2c24659a3247b3

The implementation does differ but should generally achieve the same functionality. It currently doesn't do anything with regards to folders but will likely try and do that later on. Will close this PR.

**Pull request closed without merging**
