### PR TITLE
Add pattern/tech analysis information in 1 Player mode.

### PR DESCRIPTION
**Pull request by teejusb**
This fills in the empty space.

image

Uses the algorithm provided by https://github.com/Simply-Love/Simply-Love-SM5/pull/271 so shoutouts to bblum~

### CODE REVIEW

**Comment by teejusb** [comment]
Widescreen spacing:

image

**Comment by Horsey-** [comment]
Why not center the left side panes in widescreen mode in the blank space instead of aligning them arbitrarily with the edge of the blue steps pane for player 1?

**Comment by teejusb** [comment]
That's out of scope for this PR. I'm maintaining the behavior of the current layout.
image

**Comment by bblum** [comment]
hyyyyyyype

**Pull request merged**
