### PR TITLE
Group/Folder name, Step Description/Chartname functionality

### PR DESCRIPTION
**Pull request by Horsey-**
Dan, I've just plainly started from scratch so that I don't have to worry about any messy commits. I've learned a lot about Git today, and I think I understand better how it works. Hopefully this pull request is easier for you to review. 

I have already started looking into Lambda, but in the meantime, I wanted to push a few things here so that we can get the ball rolling on a few Stepmania chart features I want to go public. Everyone uses your Simply Love theme at the moment, and really want there to be a way for people to explore the new steps metadata in SM5 (Description/Chartname). My work for the r21 dropbox has been exhausting cleaning up bad use of the credit metadata mucked up with step density. Hopefully this will move stepartists to credit themselves while not feeling constrained. My hopes are that in the future, especially Lambda, that I will add a "sort by stepartst", whereby that requires that stepartists stop filling the credit metadata with things other than their stepartist name. I'd like to get a few more things out to your master, but if I were to ask nothing more of you, these two commits would be it. Hope you have a good rest of your weekend =]

### CODE REVIEW

**Comment by dguzek** [comment]
## Regarding Git

Git is complicated and takes a while to learn.  I'm glad to hear you spent some time with it yesterday. 👍

It seems you are still committing directly to your master branch, however, so you may want to read about [the git branch command](https://www.atlassian.com/git/tutorials/using-branches) for the future.

## Regarding Lambda/other Themes

I'm very glad to hear you've started to look into Lambda.  As I've already written:

> I'll note that the StepMania community would definitely be better served were you to put your effort into a new theme rather than continuing to endlessly support Simply Love. Your commits here contain messages like "this is the future," and I think we can agree that Simply Love is decidedly **not** the future.

You should consider reaching out to @ListenerJubatus if you haven't already.

## Regarding StepMania Theming

I understand your impatience to "get the ball rolling on a few Stepmania chart features I want to go public" but please try to remember that StepMania theming is a slow process.

I worked on SL's initial release version for eighteen months in a vacuum.  If you are not prepared to spend hundreds of hours in the company of only your computer, you should probably consider other hobbies.

## Regarding This Pull Request

The commits in this pull request are considerably more compact and neat than yesterday's.  That's a great start.  👍  

Your summary text (above) is still not particularly helpful, and I ultimately found it easier to add your repository as remote, create a local branch for your remote master branch, and try to find the new features in StepMania rather than reading through changes spread across 16 files.  It's not that this pull request is too broad in scope (like before), but I could not readily discern what the changes were by reading your above summary.

Screenshots often go a long way, and GitHub makes it pretty easy to add them to pull requests like these.

## Regarding The Features

From what I can discern, this pull request:

  * adds a new Quad to SSM for group/folder name (slightly resizing other elements to accommodate?)
  * adds a new Quad to Eval for group/folder name
  * adds and uses a new png asset, stepartistbubble.png
  * adds a new ThemePref for displaying the group or filesystem folder name

I personally do not like how the two new Quads in SSM and Eval change the aesthetic of those screens.

I also do not see these features as a useful or helpful addition to the theme, but I also felt that way about the judgment scatterplot, about the judgment histogram, about highscore lists on ScreenEval, about letter grades in the MusicWheel, about the pacemaker, etc.  For better or worse, other people seem to have just eaten those up, and summed, all those features added over time are probably how I've created the current monster that is Simply Love for SM5.

I have to wonder how and when it will end.  I don't see how it will unless I stop it.

I am not interested in merging this pull request at this time.

**Comment by Horsey-** [comment]
would you consider pulling the step description enhancements by itself?

**Comment by Horsey-** [comment]
What if I resized the Eval banner a small amount to give it more whitespace?

**Comment by dougshell** [comment]
After merging this with my own fork and mucking around a bit with the proposed changes, I have to admit that I see very little (functionally zero) draw back from these changes. They add very useful information as i OFTEN see people asking about a songs origin after someone posts a screenshot. 

With regard to the added "Theme" option on the main screen, this serves quite a bit less of a purpose, but for a home player it has it's usefulness. Unfortunately, Simply Love is overwhelmingly targeted at Arcade/Dedicab users, and this change (as Dan would say) "not be appropriate"

**Comment by Horsey-** [comment]
> added "Theme" option

That's on my Home Branch, and its changes would not (should not unless I'm misunderstanding git's branches functionality?) be anywhere in this pull request. 

~~Although added a themes option to the title screen doesn't affect anyone unless the theme is put into home mode, so I don't see what harm it does.~~

**Comment by dougshell** [comment]
Wasn't even thinking about home mode. Yeah, this is an auto merge imho.
Where is you clock commit?

**Comment by Horsey-** [comment]
The bottom bar clock begs many questions to be asked. I'm about to commit it to my Event-Mode-Clock branch.

Relevant questions here are as follows:

-Do we want the clock in 12 hour or 24 hour format? I personally use 24 hour time
-Do we want the date, if so how do we format it? I personally do, but I can see why others wouldn't
-Do we want the clock in Miso Font (to match the USB/Local profile text)? I'd say miso if we include the date, and Wendy if not
-Which screens do we want the clock to appear on? I personally say that it should appear on these: 

> ScreenSelectMusic, ScreenTitleMenu, ScreenSelectColor, ScreenSelectStyle , ScreenSelectPlayMode, ScreenSelectPlayMode2, ScreenPlayerOptions, ScreenPlayerOptions2, ScreenEvaluationStage

-Do we want want to have a different clock format for the Evaluation Screen? I say that the bottom bar clock looks bad on Evaluation. I'd personally use the Wendy font on that screen only instead (remember, in this theme, Evaluation is one of the few screens that don't have the bottom white bar on it, so the aesthetics will be different)

All that said, I'm finishing up the commit, and will have it live before I go to bed.

**Comment by dougshell** [comment]
I don't have the screens to look at while I am at work, but certainly I
would hope that support for both 12hour and 24hour clocks would be added.

Date could be a configurable option as well, if it isn't too much work.

 I don't feel that any theme additions alone be forced until user
desire/acceptability is determined.

**Comment by Horsey-** [comment]
clock localization is probably a bit advanced for this theme, but I'll explore a date/time preference screen if Dan is willing to commit this and the clock pull request

**Comment by dougshell** [comment]
Clock localization? Wouldn't your just pull from system time. That would be
the simplest solution

**Comment by Horsey-** [comment]
we should probably continue this conversation in the comments of that commit to not be too off topic for this here

**Comment by Horsey-** [comment]
Doug, I committed this clock functionality to my fork here: https://github.com/Horsey-/Simply-Love-SM5/commit/b302cf91dd8d80085afdcb4c7ffb42e3f3b5d160

**Pull request closed without merging**
