### PR TITLE
WIP: Japanese translation

### PR DESCRIPTION
**Pull request by 0b5vr**

### CODE REVIEW

**Comment by dguzek** [comment]
ありがとうございます！

**Comment by FMS-Cat** [comment]
image

I left them except description stuff, since it's too difficult to maintain consistency between translation of SM5 itself and ours; it makes ours like, some parts are translated well but other parts in equal tier are not

It's true that some modifier items in Simply Love are using relatively difficult English (for us) e.g. "Subtractive Scoring", "Hide Rest Counts", "Change Extra Modifiers"... 😖 

Referencing DDR modifier menu, the "keys" are written in Japanese but "values" are left in English.

https://www.google.com/search?q=DDR+%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3&tbm=isch

SM5 default theme does not translate entire items in modifier menu except descriptions though:

image

**Comment by FMS-Cat** [comment]
this link might be helpful for you:
https://github.com/dguzek/Simply-Love-SM5/compare/6180b984...FMS-Cat:languages-japanese

**Comment by dguzek** [comment]
Thank you for all your hard work on this!

My Japanese comprehension is not very good (😅) but I will review this soon.

**Comment by dguzek** [comment]
Thank you for your hard work on this!

I am going to merge this pull request now.  If anything (specific wrapping issues, edits to ja.ini, etc.) is needed in the future, that can be addressed at that time.

**Pull request merged**
