### PR TITLE
Added optional legacy NPSGraph

### PR DESCRIPTION
**Pull request by Fieoner**
I found out that some players (and me lol) prefer how the npsgraph used to look like before with bars representing individual measures instead of points.
Some people might want to keep using the new style so I made it into a theme preference.

### CODE REVIEW

**Comment by dguzek** [comment]
Can you clarify what these changes do?  I don't understand based on your description.

**Comment by dguzek** [comment]
I've looked over the code changes, and I *think* I know what the visual difference will be in-theme, but I don't know, and the description provided in your pull request does not make it clear.

Please elaborate if you can.  Some topics that will help include:

• What did the NPS Histogram look like before I changed it?
• When did I change it?  Provide a git hash.
• Why did I change it? Read related inline comments, check commit messages, search past pull requests, etc., for context.
• What does the NPS histogram currently look like right now (without this pull request applied)?
• What does it look like with your proposed changes in place?
• Does it make sense, in your opinion, to make this configurable as a ThemPref?  Why?

Additionally, I am interested to know what kinds of hardware you have tested these changes on.  I don't necessarily need to know specific processor and monitor models, but information like

• tested on a stock MK9 unit outputting to a GX CRT at 640x480, performs + looks good
• tested on a modern gaming PC outputting to a 42" 16:9 LCD, performs + looks great
• etc.

helps me understand how these changes might be received by the existing userbase.

**Comment by dguzek** [comment]
I think this might have been autoclosed by the recent 4.8.5 release.  Sorry about that.

**Comment by Fieoner** [comment]
I've been kinda busy lately and I don't have proper internet connection at home atm but I'll try to get back to this as soon as possible

**Comment by dguzek** [comment]
No problem; take your time.

**Comment by Kauhsa** [comment]
Based on the description, I've had a similar change in my fork that we use in our arcade (and I guess was used by other people as well, at least at some point). We still do it, the current version is shown here https://github.com/Kauhsa/Simply-Love-SM5/commit/8ddbbb8a8c9a3d766f1383876b6640207b4e79f1. Perhaps there is a confusion about what feature has been in official release and what hasn't?

Originally I made this change just because I personally preferred the aesthetic – it felt right because Simply Love is quite "blocky", after all – but maybe you could make an argument that it's easier to see where streams exactly start and end, because they quite often do that exactly on the edge of measure (and a single measure is the maximum "resolution" of the NPS calculation anyway). But at least my implementation came at the cost of extra vertices, so I didn't feel like it's something that necessary should be that way in upstream.

**Comment by dguzek** [comment]
Thanks for the response, @Kauhsa.  I have not yet tested the changes in this PR, but I did have a sense they would make density graphs "blockier" (4 vertices per measure rather than 2).

I was pretty sure that mainline Simply Love had never used "blocky" density graphs, but I am also a forgetful assortment of slowly decaying bones and tissue.  

There was also the hope that this PR could be an OSS learning experience.  Keeping track of which forks introduce certain features is complicated, even for devs.  It seems entirely unreasonable to expect any user to have to care.  They just want to play a free game. 🙂

---

> my implementation came with a cost of extra vertices

This was my only reservation from the start.  This is why I chose to implement it the way I did (though that was not clear anywhere but my own mind).

**Comment by dguzek** [comment]
Any updates on this, @Fieoner?  

It is okay if you haven't had the time or interest to respond [my questions](https://github.com/dguzek/Simply-Love-SM5/pull/158#issuecomment-518820156) as they are many and complicated.  

I did not realistically expect you to have an answer for each of them.  I had hoped it might illustrate what should be considered when adding new features to software used by thousands of people with varying expectations of what the software should do on a broad range of hardware.  It will never be perfect, but we need to always try our best to ensure it will be usable by everyone.

StepMania theming in a production-ready way like this is complicated.  There are never clear answers, it's miserable work, and it doesn't even pay well.  🙂

I appreciate the helpful spirit of your pull requests, I encourage you to submit more in the future if you are inclined.  If you do, I will ask you to think critically about how the post-ITG community at large might interact with and respond the changes you are proposing at that time, and it is my hope that we can reach an amicable conclusion.

**Comment by Fieoner** [comment]
Most of my changes are inspired on @Kauhsa 's fork. This is one of them.
the histogram now looks like this image
the "legacy" option would make it look like this 
image
Both look good on our setup (1920x1080 40'' tv) and on every dedicab at eurocup 2018 (I  believe 2 of them used the stock monitors and one had a 4:3 lcd at god knows what resolution)

I made it a themepref because I assumed that if almost nobody complained about this change they would be happy with the new graph, but in spain everyone wanted the old one so it wouldn't hurt to be able to choose.

I tried to find when this change was made but I'm really having a hard time searching through the commits D:

Also I updated my fork to 4.8.5 and adapted the changes on this pr to 4.8.5 just today so if you want I can make a new one that works with the current version.

**Comment by dguzek** [comment]
> I tried to find when this change was made but I'm really having a hard time searching through the commits D:

This particular change does not exist in this repo and never did, so you won't find it in the Git commit history here.  

But, that would not necessarily be apparent even if my commit messages from 4.8.3 through 4.8.5 weren't an ergodic labyrinth of literature and poetry that disqualifies me from ever applying for employment as a programmer.

---

At the time you submitted this pull request, I was discouraged by some of the changes you'd made in your fork of SL as they seemed strange and irreverent to me.  And that in itself is okay.  There are numerous forks of my work on and off GitHub that I don't think are a good idea, but they can exist; that's open source.

I was also intrigued that you'd said you preferred "how the npsgraph used to look like" since it had never looked that way, suggesting my efforts to be responsible for Simply Love had failed – you were attributing changes I hadn't made to me, indicating you preferred something I hadn't done.  This has happened before too.  Code and feature authorship are difficult to keep track of, and can be annoying when the unknowing public sends me bug reports about things I didn't cause in forks I didn't author, but again, that comes with the territory in open source.

But finally you were, quite frankly, just disrespectful to me about changes I had had clearly made and was responsible for.  The 4.8.3, 4.8.4, and 4.8.5 releases really took a toll on me.  Over a span of four months, I used over 400 hours of my time programming things for SL, spent thousands of dollars out of my pocket paying other artists, musicians, programmers, and translators for their contributions so players could enjoy the releases, and lost way too many hours of sleep compounded by [irl grieving](https://github.com/dguzek/Simply-Love-SM5/compare/4de6eb38d0892bd05f88d9a4be5fc75171a0f5e4...1ebad20ef4399879939b5911ec3d9e933001087c).  Your only response to all this ("why????????" because you disagreed with my decision to enforce TWA) just came across as entitled and rude.  

I'm not asking for everyone to thank me for this, or even agree with the work I do, but I also don't believe I need to entertain people who are blatantly rude.  At that time, I believed you had been blatantly rude to me.  I concluded we had very different, if not incompatible, views and priorities on everything from open source dance games to life.

So, given all that, I genuinely did not know why you submitted pull requests.  I questioned your motives and wondered if this was some kind of stunt.  

I tried to illustrate that I take this project seriously, including the code, the features, the aesthetic design, the words I choose to convey these things to the public, and even the very silly giggle-inducing contributions of others.  

And yeah, a lot of my code performs badly, and the aesthetics aren't DDRA, and the features aren't RH, and my words are too often riddled with self-imposed uncertainty and doubt.  I know.  But I still take it all seriously.  I try to consider every angle I can.  

I try.

Curiously, you responded, and you were polite, and your words and screenshots suggested that you are taking this seriously too.

I'm not sure what to do now.

**Comment by Fieoner** [comment]
Since we were using what I'm calling the "old npsgraph" at eurocup 2018 I just assumed that you changed it instead of implementing it in a different way for your repo and that was a mistake on my part.
Also my fork is full of features (if you can call them that lol) that I just wanted to use for a very specific purpose (like pass percentage for the parallax challenge), I thought it would be funny to have (like Rems screaming "Allez" when Danger is on), experimental stuff that most likely nobody will care about (NECFA mode with just fantastics) or ways to add more info about how you are playing that make ScreenGameplay and ScreenEvaluation look bad  because of how I just crammed info all over them (like breakdown of misses per arrow on the scatterplot that only works on dance-single).
I'm even looking into making a mostly unplayable version of the theme called simply bad (and putting it in our public cab for april fools) inspired on this mario 64 hack https://www.youtube.com/watch?v=k4yN1xC8N3o.
It's pretty obvious that we have very different views on this but as a player I take ITG very seriously and I too care about simply love and stepmania and I want to make it easier for everyone to have the functionalities that could potentialy help them become better players or just be more confortable playing the game.
I'm sure there's a lot of people complaining about every decision you make on the theme (like removing twa as an option haha) and that it's impossible to please everyone, but in my case the thing that I care about the most in regards to "what I would like simply love to have" is functionality and customization of such functionality and that's why I also added the option to just not use the changes I made as a theme option.

PS: If this was some kind of stunt I would have probably tried to replace a mode some unplayable stuff like NECFA

**Comment by dguzek** [comment]
Thank you for responding.

I don't have the capacity as a human to fairly process this topic right now, so I am going to leave this PR open and perhaps revisit it someday in the future.

**Comment by quietly-turning** [comment]
I'm not sure I'll ever meaningfully resolve what this pull request came to represent for me at that time in my life, but perhaps if I close it, I can learn to let go.

Thank you for bearing with me, and continuing to be alive out there.

**Pull request closed without merging**
