### PR TITLE
Support horizon mode

### PR DESCRIPTION
**Pull request by aeubanks**
Some of the sizes are slightly off, but that can be fixed later if needed.

### CODE REVIEW

**Comment by quietly-turning** [comment]
Thanks for this pull request.  I appreciate your efforts to contribute and help.

---

> Some of the sizes are slightly off, but that can be fixed later if needed.

Can you please clarify what you mean by this?  What sizes?

---

Are you able to contribute a new graphic for Simply Love's title screen?
i.e. https://github.com/quietly-turning/Simply-Love-SM5/tree/4a3447bf7e5b4fe485cf93af44435fe25d3280b2/Graphics/_logos

Are you able to contribute new graphics and code for Simply Love's SelectPlayMode?
i.e. https://github.com/quietly-turning/Simply-Love-SM5/blob/4a3447bf7e5b4fe485cf93af44435fe25d3280b2/BGAnimations/ScreenSelectPlayMode%20underlay/GameplayDemo.lua

Have you tested ScreenTestInput in Horizon mode?  Have you tested the TestInput pane in ScreenEvaluation and overlay in ScreenSelectMusic?

---

Can you talk about how you've tested this within Simply Love?

Can you talk about how players should use Horizon mode within Simply Love going forward?

---

In general, this is appreciated, but it seems incomplete as-is.  There are multiple immediate tasks remaining, and it is unclear what testing you've done.

Additionally, this does not offer a clear path forward for players to understand and use Horizon game mode, and introduces significant features for active devs (in this case, me) to support.

Finally, StepMania itself does not support Horizon mode at this time.  Related: https://github.com/stepmania/stepmania/pull/2051

**Comment by aeubanks** [comment]
> Thanks for this pull request. I appreciate your efforts to contribute and help.
> 
> > Some of the sizes are slightly off, but that can be fixed later if needed.
> 
> Can you please clarify what you mean by this? What sizes?

Some of the values in SL-Helpers.lua might not be perfect.
> 
> Are you able to contribute a new graphic for Simply Love's title screen?
> i.e. https://github.com/quietly-turning/Simply-Love-SM5/tree/4a3447bf7e5b4fe485cf93af44435fe25d3280b2/Graphics/_logos

I'm no artist, but it defaults to techno's 8 panel image which seems good enough for now. Maybe in the future if somebody is interested in making a 9 panel image that would be good.
> 
> Are you able to contribute new graphics and code for Simply Love's SelectPlayMode?
> i.e. https://github.com/quietly-turning/Simply-Love-SM5/blob/4a3447bf7e5b4fe485cf93af44435fe25d3280b2/BGAnimations/ScreenSelectPlayMode%20underlay/GameplayDemo.lua

Ditto.
> 
> Have you tested ScreenTestInput in Horizon mode? Have you tested the TestInput pane in ScreenEvaluation and overlay in ScreenSelectMusic?

ScreenTestInput works, but without the graphics. It prints out buttons currently pressed in text form.
I'm not familiar with a test input in the evaluation screen?
The overlay in ScreenSelectMusic does not appear as an option.
> 
> Can you talk about how you've tested this within Simply Love?

I've watched and played a bunch of 9 and 18 panel charts. This works for the main use case, which is playing charts.
> 
> Can you talk about how players should use Horizon mode within Simply Love going forward?

I don't understand the question, isn't it just another selectable mode?
> 
> In general, this is appreciated, but it seems incomplete as-is. There are multiple immediate tasks remaining, and it is unclear what testing you've done.

It seems unreasonable to have everything perfect in one patch. In this current form, SL supports horizon without any gameplay issues, which is really the most important part. If people ever want to fix up the remaining nice-to-haves that's ideal, but in this current form it does basically everything you'd want it to do, and people can have fun with it :)
> 
> Additionally, this does not offer a clear path forward for players to understand and use Horizon game mode, and introduces significant features for active devs (in this case, me) to support.

Again, I don't understand the first part. It's a mode just like 4/5/8/10 panel.
The diff is fairly small, and if you ever feel overly burdened by horizon support in the future, I'm ok with the removal of this. I'd just like to put it in the mainline and see how people use it. If people start complaining and you don't like that, just remove it :)
> 
> Finally, StepMania itself does not support Horizon mode at this time. Related: [stepmania/stepmania#2051](https://github.com/stepmania/stepmania/pull/2051)

Of course, this is all dependent on that being accepted.

**Comment by quietly-turning** [comment]
Thanks for getting back to me on this.  Your eagerness to help is appreciated.

> I'd just like to put it in the mainline and see how people use it. If people start complaining and you don't like that, just remove it :)

I appreciate your optimism very much.

Unfortunately, I'm going to postpone thinking about this at least until after the next SL release, 4.9.1, which itself has no ETA right now.  I consider the changes this pull request represents to be a large new set of features, and I'll need time to properly test and document them for players.

**Comment by aeubanks** [comment]
> Unfortunately, I'm going to postpone thinking about this at least until after the next SL release, 4.9.1, which itself has no ETA right now. I consider the changes this pull request represents to be a large new set of features, and I'll need time to properly test and document them for players.

Sounds good :)

**Pull request closed without merging**
