### PR TITLE
Rewrite descriptions of fail types

### PR DESCRIPTION
**Pull request by sukibaby**
This would change the alt text on the fail types to appear like so:

Screenshot 2024-08-20 165239

I don't have EndOfSong pulled out of the theme in this PR.

### CODE REVIEW

**Comment by teejusb** [comment]
The groovestats note should go below the descriptions.

Also pulling it out in the same PR is preferred.

**Comment by sukibaby** [comment]
> The groovestats note should go below the descriptions.
> 
> Also pulling it out in the same PR is preferred.

Will do - setting this to draft and will reopen when the other commit is ready.

**Comment by sukibaby** [comment]
Actually removing EndOfSong will be an ITGmania PR btw, as the FailType enum is handled by the engine:

image

**Comment by teejusb** [comment]
Don't remove it from the engine. Making it inaccessible from the theme should be sufficient. You'd be breaking backwards compatibility.

**Comment by sukibaby** [comment]
> Don't remove it from the engine. Making it inaccessible from the theme should be sufficient.

I'm working on it, but looks like it won't be as straightforward as I initially thought. I'm currently contemplating the best way to prevent SL from displaying it.

image

**Comment by teejusb** [comment]
Dw about it. I can take care of it. Just open an issue so I remember.

**Comment by sukibaby** [comment]
> Dw about it. I can take care of it. Just open an issue so I remember.

Thank you! I repushed with the re-ordered text so i'll open this so you can merge it when it's ready.

**Comment by teejusb** [comment]
I mean you can close this PR and I can tackle it myself -- since I'll do everything together.

**Pull request closed without merging**
