### PR TITLE
ScreenOptionsService: Add ClearCredits option

### PR DESCRIPTION
**Pull request by concubidated**
This would be quite helpful for those of us who run this on locations.

### CODE REVIEW

**Comment by dguzek** [comment]
Out of genuine curiosity, in what sort of circumstances would you want to clear the credits from a public machine?

**Comment by ianklatzco** [comment]
We periodically have an issue where we'll take the machine out of event/home mode and back into pay mode, and then we have to clear the credits.

We typically solve this by killing & restarting Stepmania.

**Comment by dguzek** [comment]
Hmm, I'm not sure I understand the usefulness of this option, and I'm generally very reluctant to add more rows to any of the menus.  Maybe I'll merge it later today but hide the row when SM5 is not in `CoinMode_Pay`.  Would that be okay, @concubidated?

**Comment by dguzek** [comment]
> we once had an issue where device enumeration came up backwards and start turned into insert coin

What a bug! 🙂 

Thanks for the persistent coins feature; it's immensely appreciated at the public machine I help maintain.

I'll merge this later today (hopefully) and add some logic to hide the line when not in CoinMode_Pay.

**Comment by dguzek** [comment]
Apologies for sitting on this as long as I have; my attention became tied up in releasing my visual novel for SM5. 

I'll try to merge this later today and add the changes I proposed.

**Pull request merged**
