### PR TITLE
Add clear and FC lamps to the SelectMusic screen

### PR DESCRIPTION
**Pull request by dgraham573**
I compiled code from thr DDR A SM5 theme and edited some graphics to make a functional clear lamp feature for Simply Love. This mod displays a vertical bar next to the song that has a color corresponding to the type of clear: white for no FC, green for FC with greats, yellow for FEC, blue for quad, and shiny blue for quint (FA+ only). 

I've put together the necessary files and included instructionf for installing the mod to the latest version of Simply Love in this zip file. https://www.dropbox.com/s/xj4svjqftieym8g/SL%20Clear%20Lamp%20Mod.zip?dl=0

Maybe one of you guys can clean up this code to be more efficient and add it to mainline Simply Love? It would be a neat addition in my opinion!

Preview of the mod in action: https://youtu.be/i4ugDb55xuY

### CODE REVIEW

**Comment by ianklatzco** [comment]
this is a cool idea! there's a challenging design issue in that — in ddr, every song has full difficulties. that's not the case here. so, lamps flicker in and out as you jump between the different difficulties. ideally, as you scroll, the lamps would stay pegged on a partic. difficulty. solving that design issue might be the appropriate in next step.

this PR is rendering really weirdly -- looks like you may have merged changes in a strange way that caught a bunch of commits? also, there's a comment from quietly-turning that's from april 8 for some reason. very strange, maybe a bug from github's new layout.

**Comment by jordando** [comment]
I wouldn't want lamps to stay pegged on a difficulty. Seeing a clear lamp on an expert chart implies to me that you've cleared that chart, not that you cleared a (perhaps non-existent) easier chart

**Comment by quietly-turning** [comment]
Thanks for putting this demo together, @dgraham573.

> I compiled code from thr DDR A SM5 theme and edited some graphics

It's important to me that SL's code and assets stay as free + open-source and properly attributed as reasonably possible.  Can you talk more about where the code came from, who wrote it, and how the graphic assets came to be?

---

Lamps for SL are on my long-term TODO list but it's unlikely I'll get around to implementing them myself this release cycle.

---

> this PR is rendering really weirdly -- looks like you may have merged changes in a strange way that caught a bunch of commits? also, there's a comment from quietly-turning that's from april 8 for some reason. very strange, maybe a bug from github's new layout.

@ianklatzco - This pull request is asking to merge my beta branch into my release branch without adding any new/unique commits.  @dgraham573 provided a dropbox link to the code that is new.

On that note, if contributing to open source projects is something that interests you, @dgraham573, you should spend some time learning about git version control and how websites (like GitHub and Bitbucket) use it to help people collaborate on code! 🙂

**Comment by quietly-turning** [comment]
Is this something you are interested in continuing to work on, @dgraham573?

**Comment by dgraham573** [comment]
@quietly-turning yes, this is something that I would like to continue working on. Sorry for my absence, I was busy these past 3 days with my sister's wedding, but I have been reading your comments and keeping up with the thread. 


> It's important to me that SL's code and assets stay as free + open-source and properly attributed as reasonably possible. Can you talk more about where the code came from, who wrote it, and how the graphic assets came to be?

I agree with this sentiment, and I can point you in the direction of the person who wrote the original lamp code. They go by KENp, or trav358, and the original thread to the DDR A sm5 theme can be found here: https://zenius-i-vanisher.com/v5.2/thread?threadid=9466

I am no expert when it comes to writing original code or understanding the full extent of how lua functions, but I have tinkered with different SM and SL assets in the past, and I used a good amount of trial and error when trying to move this code to SL and make it look presentable. As for how the graphic assets came to be, I took the already-made clear lamp graphic from the DDR A theme (found below), cropped it to fit the height of the song listings on ScreenSelectMusic, and color-coded it to match the appropriate clear type.
AllCleared_P1


> On that note, if contributing to open source projects is something that interests you, @dgraham573, you should spend some time learning about git version control and how websites (like GitHub and Bitbucket) use it to help people collaborate on code! 🙂

This is something that interests me actually, but I am pretty inexperienced when it comes to game development and working on open-source projects like SL. Where do you think I could start with learning about git version control and how the SL team functions with updates and version fixes?

**Comment by quietly-turning** [comment]
> Sorry for my absence, I was busy these past 3 days with my sister's wedding

That's okay; congrats to your sister and their spouse! 🎉

---

> I can point you in the direction of the person who wrote the original lamp code.  They go by KENp, or trav358

Thanks for documenting this.

> As for how the graphic assets came to be, I took the already-made clear lamp graphic from the DDR A theme 

Thanks for documenting this, too.

For this Simply Love project, I make a sincere effort to ensure that every line of code and every asset is properly attributed and used with permission.  *The Rabbit Hole* still exists uncomfortably outside this goal with some of its assets, but I am working on that.

It is definitely worthwhile for you to check with KENp/trav358 to see if they are okay with you sharing their work like this.

---

> I am pretty inexperienced when it comes to game development and working on open-source projects like SL.

That's okay; everyone is at some point.  I still am. 

> This is something that interests me actually

That's the part that matters.  🙂

---

> Where do you think I could start with learning about git version control

This is a super interesting question!  I stumbled through git and GitHub for many years, and more recently I've stumbled through trying to teach people how to use git and GitHub.  My perspective on this is always evolving.

I'm learning that it's very important to have a sense of *why* developers use tools like GitHub to collaborate and *how* it helps them before jumping into tutorials.

I recommend finding an active project on GitHub that interests you and poking around in its issues and pull requests.  

If you like StepMania, poke around in the issues that are [currently open](https://github.com/stepmania/stepmania/issues?q=is%3Aopen+is%3Aissue) and [already closed](https://github.com/stepmania/stepmania/issues?q=is%3Aissue+is%3Aclosed).  Look for topics that have a lot of [back-and-forth discussion](https://github.com/stepmania/stepmania/pull/1998).   

Pull requests [that have been merged](https://github.com/stepmania/stepmania/pulls?q=is%3Apr+is%3Amerged+) can be interesting.  Do any patterns emerge between pull requests that get merged versus those that get closed?

I'll definitely encourage you to poke around and observe and ask questions.  I think it's important to see if it's something you *want* to learn more about before you throw yourself into any hands-on tutorial.

---

With this established, I'll close this pull request now.

**Pull request closed without merging**
