### PR TITLE
Small but huge functionality additions

### PR DESCRIPTION
**Pull request by Horsey-**
Sorry Dan if I'm bad at github, but I wanted to submit some clean and polished commits to the master branch, namely "Theme menu for title screen", "
Steps Description and Chart Name displayed at song selection and evaluation", and "
Song Folder/Group Now Displayed On ScreenSelectMusic and ScreenEvaluation"

These commits have been tested working/appearing correctly across course mode, 4:3, 16:9, from 640x480 to 1920x1080.

### CODE REVIEW

**Comment by dougshell** [comment]
Clock? I'm sold!!!

**Comment by Horsey-** [comment]
clock isn't added in the current commit because I couldn't find a good place to put it. Personally, I'd have it in event mode where it replaces the EVENT MODE text with a clock, accross all screens. If we can come to a consensus that this is a good compromise, I'll add it back in a new commit tonight.

**Comment by dougshell** [comment]
I agree with replacing the EVENT MODE banner. I struggle to believe any
player would ever wonder what mode they were in. There is an area that
shows gameplay time which I think is also important. I would not sacrifice
playtime counter for clock

**Comment by Horsey-** [comment]
I had a thought, I could put the clock with the session timer. I'll try it out when I get home.

**Comment by dougshell** [comment]
Would increasing high score characters be appropriate? They wouldn't have
enough room in the evaluation screen, would they?

**Comment by Horsey-** [comment]
I can provide screenshots, and I haven't made a neat commit for it, but 10 characters fit just fine ( with maxwidth in a few places )

You're reading the commits backwards; I had made a bunch of messy commits when I first made this fork. Ideally I would delete the older commits before "Clean slate".

**Comment by dguzek** [comment]
Thanks for this pull request.

Similar to #73, this is vastly too broad in scope and disorganized for me to merge.  There might be some good stuff in here, but since it's all baked into single pull request, it only takes one line I disapprove of for me to reject the entire thing.

Additionally, even though roughly half of these 36 commits are just merges, that's still around 18 commit messages for me to go through.  How many unique features/fixes does this pull request actually contain?  It's impossible to quickly ascertain.

I'll offer the same advice I did in #73:

I suspect you'll find it to be much easier if you don't make your commits directly to your fork's master branch going forward.  If your pull request is merged, or if it isn't, a minor branch is easy to jettison without mucking up the history in your fork's master branch.  This should also eliminate the need to include your merges in upstream's history.

If you are still interested in contributing, I would encourage to plan out what changes you want to make ahead of time, create distinct Git branches for each of those tasks, and submit one pull request per branch.

Some good rules of thumb might be:

  * 1 unique feature or fix = 1 unique Git branch = 1 pull request
  * Don't submit pull requests with unnecessary commits that fix your own earlier mistakes.  Mistakes happen (we're all human), but they don't need their own commits.  If you've mucked up a particular branch with too many mistake fixes (that happens), start another clean branch off master, bring your working changes into that new branch in a single commit, and delete the old branch.  Alternatively, look into [squashing commits using rebase](https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/).
  * Don't submit pull requests that contain merges that kept your fork's branch on par with upstream.  In the end it's just additional noise that muddies your intent and makes others inclined to not review the potentially good work you've done.
  * If you can't neatly summarize the pull request in its title using [approximately 50 characters](https://medium.com/@preslavrachev/what-s-with-the-50-72-rule-8a906f61f09c), you're probably trying to do too much.  *Small but huge functionality additions* does not summarize what the pull request accomplishes and is thus not helpful.

**Comment by Horsey-** [comment]
sorry Dan, I'll make a new GitHub account and make the pull requests simple to read. The messyness is only because I fail to understand git fully. I'll just stay from scratch. I'll do this when i get home and request the pull after I get things in order.

**Comment by Horsey-** [comment]
start*

**Comment by dougshell** [comment]
No need to start over, just create a new branch or your fork, or refork the
original project

**Comment by dguzek** [comment]
I'll note that the StepMania community would definitely be better served were you to put your effort into a new theme rather than continuing to endlessly support Simply Love.  Your commits here contain messages like "this is the future," and I think we can agree that Simply Love is decidedly **not** the future.

From what I understand, @ListenerJubatus has expressed interest in bringing Simply Love's features into *Lambda*, the new default theme for SM5.1.  I think that sounds like a vastly better use of time and energy.  Perhaps your can help with that?

**Pull request closed without merging**
