### PR TITLE
Update pl.ini

### PR DESCRIPTION
**Pull request by JustMoneko**

### CODE REVIEW

**Comment by teejusb** [comment]
Thanks! You might want to target itgmania-beta though as beta is no longer in development. There might be some different strings between itgmania-beta and beta/release as well.

**Comment by JustMoneko** [comment]
Oh yeah, still tend to mix those, but I think I have the lines from itgmania-beta, just uploaded to the wrong branch

**Comment by teejusb** [comment]
Seems to be some conflicts with itgmania-beta...

**Comment by JustMoneko** [comment]
Well that's prob cuz someone ran machine translation when adding practice mode

**Comment by teejusb** [comment]
I can't merge this unless the conflicts get resolved

**Comment by JustMoneko** [comment]
will redo that

**Pull request closed without merging**
