### PR TITLE
Add Preference Maximum Number of Credits

### PR DESCRIPTION
**Pull request by CrashCringle12**
See: https://github.com/itgmania/itgmania/pull/61

### CODE REVIEW

**Comment by teejusb** [comment]
This needs to target the ITGmania branch and not beta

**Comment by CrashCringle12** [comment]
> This needs to target the ITGmania branch and not beta

Ah, there we go.

**Comment by teejusb** [comment]
PR looks good. Can we at least run the different language strings through like Google translate or something? I'll merge after

**Comment by CrashCringle12** [comment]
alrighty

**Review by natano — APPROVED** [review]
LGTM!

**Pull request merged**
