### PR TITLE
fix StepStatistics/DensityGraph comments

### PR DESCRIPTION
**Pull request by andrewipark**
see commit log

### CODE REVIEW

**Comment by teejusb** [comment]
Can we have a better commit message? And then I can merge

**Comment by teejusb** [comment]
Can we have a better commit message instead of just `fix` for the first line. Will merge after.

**Comment by andrewipark** [comment]
Thanks. Changed from "fix" to the title of this PR.

**Comment by quietly-turning** [comment]
> Can we have a better commit message instead of just fix for the first line

Old habits die hard. :)

Thanks for helping me cross this one off my internal TODO list, Andrew!

**Pull request merged**
