### PR TITLE
Addition of Expert mode

### PR DESCRIPTION
**Pull request by arcaneAgilmente**
Added a mode for people that want tighter timing than ECFA's default. The judgement images need to be fixed so they match up with the rest of them in terms of colour. (I just quickly threw them together for testing purposes)

### CODE REVIEW

**Comment by dguzek** [comment]
Thanks for this pull request! 🙂

First, some questions:

- What audience does this mode cater to?
- Did you intend to revert commit eabe0321a72c9b6804ecfdc4c43b39144543ea41 as part of this pull request?
- Why did you choose the TimingWindow values you did?
- Do you have any intention of creating corresponding judgment graphics?  (This is incomplete, otherwise.)

Next, some thoughts:
 
- If you make future pull requests (and I encourage you to do so!), you should consider doing your work on some git branch other than *master*; for a more nuanced explanation, see my discussion of this same issue in [pull request 99](https://github.com/dguzek/Simply-Love-SM5/pull/99#issuecomment-368139328).
- Keep in mind that this theme's intended audience is (largely) pad-players, and ECFA mode is already more difficult than 99% of my audience cares for. 🙂

Although I appreciate the effort that went into this pull request, my immediate inclination is not merge it.  I'm not sure it makes sense for the master branch and future releases to include this feature.

If you can make a compelling argument otherwise, however, I will certainly reconsider!

**Comment by arcaneAgilmente** [comment]
The mode is intended to cater to ecfa's audience, machine operators to help with syncing of cabinets, as well as the player that wants a quick and simple way to gauge their own improvement at timing without the rounded up window ECFA offers (which allows for judgements that hit the fantastic window to end up being graded as FA+/Ridiculous.


I didn't intend to revert eabe032, (I don't use github that often so I didn't notice it.)

Image editing isn't a skillset I have. (Hence the quick and dirty image editing) The reason I swapped the colours around was for a: immediate mode recognition on the result screen and b: when playing songs and attempting to FA, the blue fantastic serves as a more noticeable alert to off timing then when going from blue to grey like ECFA does. 

In terms of the images, one could just use the ECFA labels and swap the colours back around. However this does negate the above point.

Thanks for the future advice. I don't know if I have anything else to add to the theme but if I think of anything, I'll definitely keep it in mind!

**Comment by dougshell** [comment]
I will say that using EFCA mode did help me fine tune my timing a bit.

**Comment by dguzek** [comment]
@dougshell – I'm glad to hear that!  Improving your timing is half the point of ECFA mode, and I have no intentions of removing it from SL.

@arcaneAgilmente – Thanks for responding.  I am not interested in adding additional gamemodes to Simply Love at this time (at least not without an _incredibly_ compelling reason).   

With that said, the changes you made clearly made sense and were valuable to you, so I encourage you to maintain your fork with a unique (non-master) branch that includes these changes for your own purposes.  That's part of the beauty of distributed version control on open-source software projects.

**Comment by RodentVienna** [comment]
Hello,

I am closely following the ongoing development on a constant, almost daily basis.
It seems you, Dan, are more open these days to merge intersting and innovative features into master.

That said, again, thank you for your ongoing efforts!

In this case, I would have an idea:
How about letting users create custom modes themselves (with the use of a SL_custom_mode.ini)?

```
[Expert]
*parameters*

[your mode here]
*parameters*
```

it may take another rework of the mode-selection screen to accomodate for more than the current entries.

This is just to check if this sounds interesting and appealing at all to you.
the compelling reason would be, that users can then take care of their custom modes themselves.

thank you!
Alex

**Comment by dguzek** [comment]
> How about letting users create custom modes themselves (with the use of a SL_custom_mode.ini)?

This is an interesting idea, but  I am concerned that such a feature would only serve to further fragment the post-ITG community.

* "What game mode *is* that?"
* "What are *your* timing windows?"
* "So... a quad star in *your* custom game mode is still a quad star in my custom game mode, right? Or no?"
* etc.

I am genuinely concerned that allowing users to create their own game modes is a recipe for chaos.  Quite in contrast to this feature proposal, I feel strongly that the community needs more standards established and enforced.  

I also worry that this would, in reality, amount to me fielding more questions and clearing up more miscommunications.

For these reasons, I am not interested in such a feature.

**Comment by RodentVienna** [comment]
Thanks for your explanation. I can only agree on the fragmentation of the ITG community, and haven't thought about this earlier.

Thanks for looking into it!
Alex

**Pull request closed without merging**
