### PR TITLE
Change defaults from X-mod, 1.00x to M-mod, 250bpm

### PR DESCRIPTION
**Pull request by sukibaby**
M250 seems to be a good option for beginner players (compared to 1x) as 300 seems to be a bit fast for beginners. During discussions about what the ideal value here would be, some felt 300-350 is better for experienced players but 250-300 is better for beginners.

### CODE REVIEW

**Review by stclairdaniel — APPROVED** [review]
This is such an awesome change! I love anything that will make the new player onboarding smoother.

**Comment by aeubanks** [comment]
M mod by default sounds great. Why 350 specifically? (the link says 300)

Perhaps we should get some new players to comment on what scroll speed seems ok

**Comment by sukibaby** [comment]
> M mod by default sounds great. Why 350 specifically? (the link says 300)
> 
> Perhaps we should get some new players to comment on what scroll speed seems ok

I don't think there was any consensus on what speed exactly should be used, 

300 is maybe a little fast for beginners and a little slow for lots of 16ths.

I think 350 is good for being able to play a song with lots of 16ths,

Some people who have got setups ready for use at conventions etc set it for 250 and suggested that instead of 300, so maybe 250 is the better option?

**Comment by aeubanks** [comment]
if people were using 250 at conventions that seems like a good starting place, we can adjust in the future if people complain

**Comment by aeubanks** [comment]
can you put that info in the commit description?

**Comment by sukibaby** [comment]
> can you put that info in the commit description?

For sure,  i was going to update both to 250 bpm and will do this too.

**Comment by aeubanks** [comment]
I meant can you put the specific reasoning for 250bpm (people using this at conventions) in the *description* so people who read this commit if it's committed can understand the reasoning without having to look at the PR/issue comments.

Otherwise this looks great

**Comment by sukibaby** [comment]
> I meant can you put the specific reasoning for 250bpm (people using this at conventions) in the _description_ so people who read this commit if it's committed can understand the reasoning without having to look at the PR/issue comments.
> 
> Otherwise this looks great

I have this in the commit,  if it's not good please let me know, i'd be willing to change it:

" M250 seems to be a good option for beginner players (compared to 1x) as 300 seems to be a bit fast for beginners. During discussions about what the ideal value here would be, some felt 300-350 is better for experienced players but 250-300 is better for beginners. "

**Comment by aeubanks** [comment]
> > I meant can you put the specific reasoning for 250bpm (people using this at conventions) in the _description_ so people who read this commit if it's committed can understand the reasoning without having to look at the PR/issue comments.
> > Otherwise this looks great
> 
> I have this in the commit, if it's not good please let me know, i'd be willing to change it:
> 
> " M250 seems to be a good option for beginner players (compared to 1x) as 300 seems to be a bit fast for beginners. During discussions about what the ideal value here would be, some felt 300-350 is better for experienced players but 250-300 is better for beginners. "

Ah in other github projects the first comment of the PR is used as the commit description (especially with squash and merge), unsure of how it works here in itgmania. Sorry for the noise

**Comment by sukibaby** [comment]
> > > I meant can you put the specific reasoning for 250bpm (people using this at conventions) in the _description_ so people who read this commit if it's committed can understand the reasoning without having to look at the PR/issue comments.
> > > Otherwise this looks great
> > 
> > 
> > I have this in the commit, if it's not good please let me know, i'd be willing to change it:
> > " M250 seems to be a good option for beginner players (compared to 1x) as 300 seems to be a bit fast for beginners. During discussions about what the ideal value here would be, some felt 300-350 is better for experienced players but 250-300 is better for beginners. "
> 
> Ah in other github projects the first comment of the PR is used as the commit description (especially with squash and merge), unsure of how it works here in itgmania. Sorry for the noise

No worries, it's appreciated, I'd always prefer to know what the 'right' way to do things is.

**Pull request merged**
