### PR TITLE
Align Roll/Mine order to ITC2023 standards

### PR DESCRIPTION
**Pull request by beremy-codeboi**

### CODE REVIEW

**Comment by beremy-codeboi** [comment]
Admins? Can I get a review on this?

**Comment by beremy-codeboi** [comment]
@teejusb kindly ping

**Comment by teejusb** [comment]
Tbh I don't actually follow because the site has it as Holds -> Mines -> Rolls

image

**Comment by beremy-codeboi** [comment]
I see Big ITL is secretly trying to cover up the mess they created

You win this time, ITL

**Pull request closed without merging**
