### PR TITLE
Font improvements for Miso (Please Test!)

### PR DESCRIPTION
**Pull request by JustMoneko**
I regenerated the font and tweaked spacing to hopefully make it look a bit better.

Before uppercase letters were noticeably thicker than lowercase ones, so I fixed it, but I had to make changes to spacing values manually, so please test to see if I didn't break anything. Especially other languages.

I uploaded a few screenshots to demonstrate what I did.

Before:
Program Screenshot 2021 02 24 - 21 52 54 28

After:
Program Screenshot 2021 02 24 - 21 42 43 39

Before:
Program Screenshot 2021 02 24 - 21 53 16 49

After:
Program Screenshot 2021 02 24 - 21 43 10 80

Before:
Program Screenshot 2021 02 24 - 21 53 02 08

After:
Program Screenshot 2021 02 24 - 21 42 57 02

Before:
Program Screenshot 2021 02 24 - 21 53 06 66

After:
Program Screenshot 2021 02 24 - 21 54 25 88

Before:
Program Screenshot 2021 02 24 - 21 52 49 49

After:
Program Screenshot 2021 02 24 - 21 43 21 51

### CODE REVIEW

**Comment by natano** [comment]
I like the more consisten letter line widths!

I didn't have much time to look at this, but on a cursory look it seem like the lower-case letter 's' is too narrow. Lower-case 'i' also seems not to be centered, but that might just be the specific letter combination on the screenshot.

Screenshot_20210224_223817

**Comment by JustMoneko** [comment]
"s" was fixed, but the issue with "i" seems to be the "c" next to it

**Comment by JustMoneko** [comment]
Oh, and I added Hungarian glyphs in that commit as well.

Test image:
Program Screenshot 2021 02 25 - 14 46 48 29

**Comment by JustMoneko** [comment]
Now I have to admit, that I'd rushed this pull request before it was ready. I need to manually tweak font .png as well as .ini files to be at least as presentable as the old one.

To be fixed:
- [x] Standard uppercase glyphs
- [x] Standard lowercase glyphs
- [ ] All special language characters

**Comment by teejusb** [comment]
Thanks for the update! Let us know when this PR is ready.

**Comment by JustMoneko** [comment]
So I worked on this today and I tried to use newer Texture Font Generator and it turned out to be the way to go. Unfortunately this means that all of the work on this branch is obsolete. I'm going to close this PR for now, and make a new one from a completely new branch once I'm finished.

**Pull request closed without merging**
